apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  namespace: default
spec:
  clusterIP: None  # <-- This makes it headless
  selector:
    app: modular-grpc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
